EMS.Web/Controllers/DepartmentController.cs
using AutoMapper;
using EMS.BLL.Interfaces;
using EMS.DAL.Models;
using EMS.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EMS.Web.Controllers
{
    
    public class DepartmentController : Controller
    {
        
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;
        public DepartmentController(IUnitOfWork _UOW,IMapper mapper)
        {
            
            this.unitOfWork = _UOW;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var Departments = await unitOfWork.DepartmentRepository.GetAllAsync();
            var DepartmentVM = mapper.Map<IEnumerable<DepartmentViewmodel>>(Departments);
            return View(DepartmentVM);
        }
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DepartmentViewmodel model)
        {
            var Deartment = mapper.Map<Department>(model);
            if (ModelState.IsValid)
            {
                var Count =await unitOfWork.DepartmentRepository.AddAsync(Deartment);
                if (Count > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Details (int ? id)
        {
            var department= await unitOfWork.DepartmentRepository.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            var DepartmentVM = mapper.Map<DepartmentViewmodel>(department);
            return View(DepartmentVM);

        }
        [HttpGet]
        public async Task<IActionResult> Edit ([FromRoute]int id)
        {
            var department= await unitOfWork.DepartmentRepository.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
          var  DepartmentVM= mapper.Map<DepartmentViewmodel>(department);
            return View(DepartmentVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DepartmentViewmodel model)
        {
            var Department= mapper.Map<Department>(model);
            if (ModelState.IsValid)
            {
                var Count = await unitOfWork.DepartmentRepository.Update(Department);
                if (Count >0)
                {
                    return RedirectToAction("Index");
                }
               
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete (int id)
        {
            var department = await unitOfWork.DepartmentRepository.GetById(id);
            if (department == null)
            {
                return NotFound();
            }
            var DepartmentVM= mapper.Map<DepartmentViewmodel>(department);
            return View(DepartmentVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Department model)
        {
            var Count = await unitOfWork.DepartmentRepository.Delete(model);
            if (Count > 0)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

EMS.Web/Controllers/EmployeeController.cs
using AutoMapper;
using EMS.BLL.Interfaces;
using EMS.BLL.Repositories;
using EMS.DAL.Models;
using EMS.Web.Helpers;
using EMS.Web.ViewModels.Employee;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace EMS.Web.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IMapper mapper;
        private readonly IUnitOfWork unitOfWork;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {

            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string input)
        {
            var Employees = Enumerable.Empty<Employee>();
            if (string.IsNullOrEmpty(input))
            {
                Employees =await unitOfWork.EmployeeRepository.GetAllAsync();
            }
            else
            {
                Employees = await unitOfWork.EmployeeRepository.GetByNameAsync(input);

            }

            var EmployeeVM = mapper.Map<IEnumerable<CreateEmployeeVM>>(Employees);


            return View(EmployeeVM);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var departments =await unitOfWork.DepartmentRepository.GetAllAsync();

            ViewBag.Departments = new SelectList(departments, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateEmployeeVM model)
        {
            if (ModelState.IsValid)
            {

                if (model.Image != null)
                {
                    model.ImageURL = DocumentSettings.UploadFile(model.Image, "Images");
                }
                var employee = mapper.Map<Employee>(model);


                var Count = await unitOfWork.EmployeeRepository.AddAsync(employee);
                if (Count > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            var departments = await unitOfWork.DepartmentRepository.GetAllAsync();
            ViewBag.Departments =  new SelectList(departments, "Id", "Name", model.DepartmentId);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var employee = await unitOfWork.EmployeeRepository.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            var employeeVM = mapper.Map<EmployeeViewModel>(employee);
            var department = await unitOfWork.DepartmentRepository.GetById(employeeVM.DepartmentId);


            return View(employeeVM);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id) {

            var employee = await    unitOfWork.EmployeeRepository.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            var employeeVM = mapper.Map<EmployeeViewModel>(employee);
            var departments =await unitOfWork.DepartmentRepository.GetAllAsync();
            ViewBag.Departments = new SelectList(departments, "Id", "Name", employeeVM.DepartmentId);
            return View(employeeVM);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.ImageURL is not null)
                {
                    DocumentSettings.DeleteFile(model.ImageURL, "Images");
                }
                if (model.Image is not null)
                {
                    model.ImageURL = DocumentSettings.UploadFile(model.Image, "Images");
                }

                var employee = mapper.Map<Employee>(model);

                var Count =await unitOfWork.EmployeeRepository.Update(employee);
                if (Count > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            var departments = await unitOfWork.DepartmentRepository.GetAllAsync();
            ViewBag.Departments = new SelectList(departments, "Id", "Name", model.DepartmentId);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id) {
            var employee = await unitOfWork.EmployeeRepository.GetById(id);
            if (employee == null)
            { return NotFound(); }
            var employeeVM = mapper.Map<EmployeeViewModel>(employee);
            var department =await unitOfWork.DepartmentRepository.GetById(employeeVM.DepartmentId);

            return View(employeeVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(EmployeeViewModel model)
        {
            

            var employee = mapper.Map<Employee>(model);

            var count = await unitOfWork.EmployeeRepository.Delete(employee);
            if (count > 0)
            {
                if (!string.IsNullOrEmpty(model.ImageURL))
                {
                    DocumentSettings.DeleteFile(model.ImageURL, "Images");
                }

                return RedirectToAction("Index");
            }

            
            var departmentInfo = await unitOfWork.DepartmentRepository.GetById(model.DepartmentId);
            ViewBag.Department = departmentInfo;
            return View(model);
        }


    }
}

EMS.Web/Views/Shared/Auth.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/Auth.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		
		@RenderBody()

        @RenderSection("Scripts", required: true)
		<!-- copyright -->
		
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

EMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMS.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS.Web.styles.css" asp-append-version="true" />
    <style>
        /* Custom Toggler Design */
        .custom-toggler {
            padding: 0.75rem;
            transition: all 0.3s ease;
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 8px;
        }

            .custom-toggler:hover {
                transform: scale(1.05);
                box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
            }

            .custom-toggler:focus {
                outline: none;
                box-shadow: 0 0 0 3px rgba(66, 153, 225, 0.5);
            }

        .navbar-toggler-icon {
            position: relative;
            width: 1.75em;
            height: 1.75em;
            transition: all 0.3s ease;
        }

        .toggler-bar {
            position: absolute;
            width: 100%;
            height: 2px;
            background: linear-gradient(90deg, #4f46e5, #6366f1);
            left: 0;
            transition: all 0.3s ease;
        }

        .top-bar {
            top: 4px;
        }

        .middle-bar {
            top: 50%;
            transform: translateY(-50%);
        }

        .bottom-bar {
            bottom: 4px;
        }

        /* Animated X when collapsed */
        .custom-toggler[aria-expanded="true"] .top-bar {
            transform: rotate(45deg) translate(4px, 4px);
        }

        .custom-toggler[aria-expanded="true"] .middle-bar {
            opacity: 0;
        }

        .custom-toggler[aria-expanded="true"] .bottom-bar {
            transform: rotate(-45deg) translate(4px, -4px);
        }

       

       
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Management System</a>
                <button class="navbar-toggler custom-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation menu">
                    <span class="navbar-toggler-icon">
                        <span class="toggler-bar top-bar"></span>
                        <span class="toggler-bar middle-bar"></span>
                        <span class="toggler-bar bottom-bar"></span>
                    </span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EMS.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>